### ISSUE TITLE
部分幼兒園定位不正確

### ISSUE THREAD

**Issue by newbuy** [kiang/ap.ece.moe.edu.tw#2]
比如：
https://github.com/kiang/ap.ece.moe.edu.tw/blob/master/data/slip/%E8%87%BA%E5%8C%97%E5%B8%82/%E8%87%BA%E5%8C%97%E5%B8%82%E7%A7%81%E7%AB%8B%E5%A8%83%E5%A8%83%E6%9E%9C%E5%B9%BC%E5%85%92%E5%9C%92.json
地址為：        "address": "[108]艋舺大道184號2樓及186號1、2樓",

可能原因猜測：
1.缺少萬華區
2.地址有兩棟建築物

**Comment by kiang** [comment]
這個點是參考官方標示，只能就發現的部份逐一修正，感謝通報
b397678bad9a01b30dee4e26acf2f6ffc7030039
